export const planFormCopy = {
  nl: {
    steps: ["Jij en je bedrijf", "Cijfers en ronde", "Criteria", "Documenten"],
    titles: ["Over jou en je bedrijf", "Cijfers en je ronde", "Onze zes criteria", "Documenten en afronden"],
    next: "Volgende stap", previous: "Vorige", send: "Verstuur mijn plan", choose: "Kies…",
    confidential: "Je plan wordt vertrouwelijk behandeld.",
    fields: {
      name: "Naam *", role: "Functie", email: "E-mailadres *", phone: "Telefoonnummer",
      company: "Bedrijfsnaam *", website: "Website", city: "Vestigingsplaats", year: "Opgericht in (jaar)",
      fte: "Aantal medewerkers (fte)", stage: "Fase *", focus: "Domein *", market: "Markt",
      description: "Omschrijf je bedrijf in maximaal 500 tekens *", revenue: "Omzet afgelopen 12 maanden (€)",
      mrr: "Terugkerende omzet per maand / MRR (€)", customers: "Aantal betalende klanten",
      round: "Totale omvang van de ronde (€) *", amount: "Gevraagde bijdrage van Ormac (€) *",
      use: "Waar ga je het geld voor gebruiken, en welke mijlpalen wil je daarmee halen? *",
      investors: "Welke andere investeerders nemen deel of zijn in gesprek? *",
    },
    marketOptions: ["B2C", "B2B (MKB)", "B2B (enterprise)", "Combinatie"],
    roundNote: "We investeren altijd samen met andere investeerders. Vertel ons hoe je ronde eruitziet.",
    amountHint: "Seed €25k – €50k, vervolgrondes €50k – €100k, maximaal €250k per deelneming",
    investorsPlaceholder: "Nog geen is ook een antwoord",
    board: "Heb je al een advisory board, en sta je open voor een plek voor Ormac? *",
    boardOptions: ["Ja, we hebben er een", "Nee, maar we staan ervoor open", "Graag meer uitleg"],
    criteriaNote: "Geef per criterium aan in hoeverre je bedrijf eraan voldoet, met een korte toelichting.",
    criteriaQuestions: ["Is het product inzetbaar bij klanten, zonder workarounds?", "Betalen klanten een marktconform tarief op basis van een contract?", "Maken klanten er nu budget voor vrij?", "Is er technische én commerciële kracht, met volle focus?", "Kan de omzet groeien zonder dat de kosten evenredig meegroeien?", "Is het kapitaal gekoppeld aan concrete mijlpalen?"],
    answers: ["Ja", "Deels", "Nog niet"], explanation: "Korte toelichting",
    deck: "Pitchdeck * (PDF)", financial: "Financieel plan * (PDF of Excel)", otherFiles: "Overige documenten (optioneel, PDF of Excel)",
    urgent: "Mijn aanvraag heeft spoed", urgentNote: "We reageren dan binnen vijf werkdagen.", urgentWhy: "Waarom heeft het spoed? *", urgentDate: "Voor welke datum? *",
    source: "Hoe ben je bij Ormac terechtgekomen?", sources: ["Via via", "LinkedIn", "Evenement", "Startupbootcamp of andere accelerator", "Zoekmachine", "Anders"],
    privacy: "Ik ga akkoord met de verwerking van mijn gegevens volgens de privacyverklaring",
    fileError: "Kies niet-lege bestanden in het juiste formaat: maximaal 5 bestanden en 4 MB in totaal.",
    fileLimits: "Maximaal 5 documenten, samen maximaal 4 MB. Maak grotere bestanden kleiner voordat je ze uploadt.",
    successTitle: "Je plan is verstuurd",
    successNote: "Je aanvraag en documenten zijn aangeboden aan onze e-maildienst voor verzending naar Ormac. Je hoort binnen twee weken van ons, bij spoed binnen vijf werkdagen.",
    reference: "Je referentie", sending: "Bezig met versturen…", checking: "Verzendservice controleren…",
    humanTitle: "Bevestig dat je een mens bent", humanNote: "Cloudflare controleert dit om ongewenste inzendingen te voorkomen.", retryHuman: "Menscontrole opnieuw laden",
    errors: {
      unavailable: "Het formulier kan momenteel niet verzenden. Probeer het later opnieuw.",
      human: "Rond de menscontrole af voordat je je plan verstuurt. Is de controle verlopen? Doe deze dan opnieuw.",
      invalid: "Controleer de verplichte velden en je e-mailadres in alle stappen.",
      files: "Controleer je documenten: PDF of Excel, maximaal 5 bestanden en 4 MB in totaal. Het pitchdeck moet een PDF zijn.",
      rate: "Er zijn te veel verzendpogingen gedaan. Wacht 15 minuten en probeer het opnieuw.",
      delivery: "We konden de verzending niet bevestigen. Je invoer is bewaard. Rond de menscontrole opnieuw af en probeer nogmaals.",
    },
  },
  en: {
    steps: ["You and your company", "Figures and round", "Criteria", "Documents"],
    titles: ["About you and your company", "Figures and your round", "Our six criteria", "Documents and finishing"],
    next: "Next step", previous: "Previous", send: "Send my plan", choose: "Choose…",
    confidential: "Your plan will be treated confidentially.",
    fields: {
      name: "Name *", role: "Job title", email: "Email address *", phone: "Phone number",
      company: "Company name *", website: "Website", city: "Location", year: "Year founded",
      fte: "Number of employees (FTE)", stage: "Stage *", focus: "Focus area *", market: "Market",
      description: "Describe your company in no more than 500 characters *", revenue: "Revenue last 12 months (€)",
      mrr: "Monthly recurring revenue / MRR (€)", customers: "Number of paying customers",
      round: "Total size of the round (€) *", amount: "Amount requested from Ormac (€) *",
      use: "What will you use the money for, and which milestones do you want to reach with it? *",
      investors: "Which other investors are participating or in talks? *",
    },
    marketOptions: ["B2C", "B2B (SME)", "B2B (enterprise)", "Combination"],
    roundNote: "We always invest alongside other investors. Tell us what your round looks like.",
    amountHint: "Seed €25k – €50k, follow-on rounds €50k – €100k, up to €250k per company",
    investorsPlaceholder: "None yet is also an answer",
    board: "Do you already have an advisory board, and are you open to a seat for Ormac? *",
    boardOptions: ["Yes, we have one", "No, but we are open to it", "Please explain more"],
    criteriaNote: "For each criterion, indicate to what extent your company meets it, with a short explanation.",
    criteriaQuestions: ["Can the product be used at customers without workarounds?", "Do customers pay a market-rate price under a contract?", "Are customers freeing up budget for it now?", "Is there technical and commercial strength, with full focus?", "Can revenue grow without costs rising at the same rate?", "Is the capital linked to concrete milestones?"],
    answers: ["Yes", "Partly", "Not yet"], explanation: "Short explanation",
    deck: "Pitch deck * (PDF)", financial: "Financial plan * (PDF or Excel)", otherFiles: "Other documents (optional, PDF or Excel)",
    urgent: "My application is urgent", urgentNote: "We will then respond within five working days.", urgentWhy: "Why is it urgent? *", urgentDate: "By which date? *",
    source: "How did you hear about Ormac?", sources: ["Personal referral", "LinkedIn", "Event", "Startupbootcamp or another accelerator", "Search engine", "Other"],
    privacy: "I agree to the processing of my data in accordance with the privacy statement",
    fileError: "Choose non-empty files in the correct format: up to 5 files and 4 MB combined.",
    fileLimits: "Up to 5 documents, 4 MB combined. Reduce larger files before uploading.",
    successTitle: "Your plan has been sent",
    successNote: "Your application and documents have been accepted by our email service for sending to Ormac. We will respond within two weeks, or five working days for urgent applications.",
    reference: "Your reference", sending: "Sending…", checking: "Checking sending service…",
    humanTitle: "Confirm you are human", humanNote: "Cloudflare checks this to prevent unwanted submissions.", retryHuman: "Reload human check",
    errors: {
      unavailable: "The form is currently unable to send. Please try again later.",
      human: "Complete the human check before sending your plan. If the check expired, complete it again.",
      invalid: "Check the required fields and your email address in every step.",
      files: "Check your documents: PDF or Excel, up to 5 files and 4 MB combined. The pitch deck must be a PDF.",
      rate: "Too many sending attempts. Wait 15 minutes and try again.",
      delivery: "We could not confirm sending. Your entries are preserved. Complete the human check again and retry.",
    },
  },
};
